version: "3"
services:
  web:
    build:
      ../.
    links:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - webnet
  mysql:
    build:
      sql/.
    ports:
      - "3307:3307"
    networks:
      - webnet
networks:
  webnet:
