version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    build: ../.
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  mysql:
      image: mysql
      ports:
        - "3307:3306"
      volumes:
        - ./data:/data
      deploy:
        placement:
          constraints: [node.role == manager]
      networks:
        - webnet
networks:
  webnet:
